meal_plan/urls.py
from django.urls import path

# from django.contrib.auth import views as auth_views
from meal_plan.views import (
    MealPlanCreateView,
    MealPlanDeleteView,
    MealPlanUpdateView,
    MealPlanDetailView,
    MealPlanListView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plan_list"),
    path("create/", MealPlanCreateView.as_view(), name="meal_plan_create"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="meal_plan_detail"),
    path("<int:pk>/edit/", MealPlanUpdateView.as_view(), name="meal_plan_edit"),
    path(
        "<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plan_delete",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plan/", include("meal_plan.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plan/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="mealplan",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField(
        "recipes.Recipe", related_name="meal_plans"
    )

meal_plan/forms.py
from django import forms
from django.forms import ModelForm

from .models import MealPlan


class DateInput(forms.DateInput):
    input_type = "date"


class MealPlanForm(ModelForm):
    class Meta:
        model = MealPlan
        fields = ["name", "owner", "date", "recipes"]
        widgets = {
            "date": DateInput(),
        }

meal_plan/views.py
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from meal_plan.forms import MealPlanForm
from meal_plan.models import MealPlan

# Create your views here.


class MealPlanListView(ListView):
    model = MealPlan
    template_name = "meal_plan/list.html"
    # paginate_by = 2


class MealPlanCreateView(CreateView):
    model = MealPlan
    template_name = "meal_plan/create.html"
    # fields = ["name", "recipes", "date"]
    # success_url = reverse_lazy("meal_plan_detail")
    form_class = MealPlanForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("meal_plan_detail", args=[self.object.id])


class MealPlanDetailView(DetailView):
    model = MealPlan
    template_name = "meal_plan/detail.html"


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plan/edit.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meal_plan_list")


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plan/delete.html"
    success_url = reverse_lazy("meal_plan_list")


# class PromiseCreateView(CreateView):
#     model = Promise
#     form_class = PromiseForm

meal_plan/templates/meal_plan/create.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <input type="submit" value="Create" />
      </div>
    </form>
  </main>

{% endblock content %}

meal_plan/templates/meal_plan/delete.html
{% extends 'meal_plan/main.html' %}

{% block content %}
<main>
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ recipe }}"?</p>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>

{% endblock content %}

meal_plan/templates/meal_plan/detail.html
{% extends 'meal_plan/main.html' %}

{% block content %}

  <main class="recipe-detail">
    <div>
      <a href="{% url 'meal_plan_edit' mealplan.id %}">Edit</a>
      <a href="{% url 'meal_plan_delete' mealplan.id %}">Delete</a>
    </div>
    <h2> {{mealplan.name}} </h2>
    <div>


    {% for recipe in mealplan.recipes.all %}
        <p>
            <a href="{% url 'recipe_detail' recipe.pk %}">{{recipe.name}}</a>
        </p>
    {% endfor %}
    </a>

    </div>
  </main>

{% endblock content %}

meal_plan/templates/meal_plan/edit.html
{% extends 'meal_plan/main.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
{% endblock content %}

meal_plan/templates/meal_plan/list.html
{% extends 'meal_plan/main.html' %}

{% block pagination %}
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
{% endblock pagination %}


{% block content %}
<main class="recipe-grid">
    {% for mealplan in mealplan_list %}
    <a href="{% url 'meal_plan_detail' mealplan.id %}">
    <li>
        {{mealplan.name}}
    </li>
    </a>
    {% endfor %}

    <a href="{% url 'meal_plan_create' %}"> create a meal plan
    </a>


</main>

{% endblock content %}

meal_plan/templates/meal_plan/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>New Recipe - Scrumptious</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li>
            <a href="{% url 'home' %}">Scrumptious</a>
          </li>
          <li>
            <a href="{% url 'tags_list' %}">Tags</a>
          </li>
          <li>
            <a href="{% url 'recipes_list' %}">Recipe</a>
          </li>
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'logout' %}">Logout</a>
          </li>
          {% endif %} {% if user.is_staff %}
          <li>
            <a href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% block pagination %} {% endblock pagination %}
    </header>
    {% block content %} {% endblock content %}
  </body>
</html>